#!/usr/bin/env python3
"""Ba Zi (Four Pillars of Destiny) calculator.
Pure Python stdlib. Reads JSON from stdin (or --file), writes JSON to stdout.
Also supports CLI named arguments (--year, --month, etc.).
"""

import argparse
import json
import sys
import io
from datetime import date, timedelta
from typing import Optional, Union

# Force UTF-8 stdout to prevent encoding issues on Chinese Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# ============================================================
# Data Tables
# ============================================================

STEMS = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
BRANCHES = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]
ELEMENTS = ["木", "木", "火", "火", "土", "土", "金", "金", "水", "水"]
STEM_YY = ["阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴"]  # yin/yang
# 五行相生相克
GEN_BY = {  # generated by: key is generated by value
    "木": "水", "火": "木", "土": "火", "金": "土", "水": "金"
}
CTRL_BY = {  # controlled by: key is controlled by value
    "木": "金", "火": "水", "土": "木", "金": "火", "水": "土"
}

# 纳音 - 60 entries (each pair shares one name, so 30 unique names x2)
NAYIN = [
    "海中金", "海中金", "炉中火", "炉中火", "大林木", "大林木",
    "路旁土", "路旁土", "剑锋金", "剑锋金", "山头火", "山头火",
    "涧下水", "涧下水", "城头土", "城头土", "白蜡金", "白蜡金",
    "杨柳木", "杨柳木", "泉中水", "泉中水", "屋上土", "屋上土",
    "霹雳火", "霹雳火", "松柏木", "松柏木", "长流水", "长流水",
    "沙中金", "沙中金", "山下火", "山下火", "平地木", "平地木",
    "壁上土", "壁上土", "金箔金", "金箔金", "覆灯火", "覆灯火",
    "天河水", "天河水", "大驿土", "大驿土", "钗钏金", "钗钏金",
    "桑柘木", "桑柘木", "大溪水", "大溪水", "沙中土", "沙中土",
    "天上火", "天上火", "石榴木", "石榴木", "大海水", "大海水",
]

# 地支藏干 (hidden stems in each branch) - list of (stem_idx, strength)
# Strength: 本气, 中气, 余气
HIDDEN_STEMS = {
    0: [(9, "本气")],                          # 子: 癸
    1: [(5, "本气"), (9, "中气"), (7, "余气")],  # 丑: 己癸辛
    2: [(0, "本气"), (2, "中气"), (4, "余气")],  # 寅: 甲丙戊
    3: [(1, "本气")],                          # 卯: 乙
    4: [(4, "本气"), (1, "中气"), (9, "余气")],  # 辰: 戊乙癸
    5: [(2, "本气"), (6, "中气"), (4, "余气")],  # 巳: 丙庚戊
    6: [(3, "本气"), (5, "中气")],              # 午: 丁己
    7: [(5, "本气"), (3, "中气"), (1, "余气")],  # 未: 己丁乙
    8: [(6, "本气"), (8, "中气"), (4, "余气")],  # 申: 庚壬戊
    9: [(7, "本气")],                          # 酉: 辛
    10: [(4, "本气"), (7, "中气"), (3, "余气")], # 戌: 戊辛丁
    11: [(8, "本气"), (0, "中气")],             # 亥: 壬甲
}

# Branch element mapping: 子丑寅卯辰巳午未申酉戌亥
BRANCH_ELEMENTS = ["水", "土", "木", "木", "土", "火", "火", "土", "金", "金", "土", "水"]

# 60-cycle index map: (stem_idx, branch_idx) -> cycle_idx (0-59)
NAYIN_IDX_MAP = {}
for i in range(60):
    s = i % 10
    b = i % 12
    NAYIN_IDX_MAP[(s, b)] = i

# 五虎遁: year_stem -> first month stem (寅月干)
# 甲己之年丙作首, 乙庚之年戊为头, 丙辛之年庚起, 丁壬之年壬起, 戊癸之年甲起
FIVE_TIGER = {0: 2, 5: 2,  1: 4, 6: 4,  2: 6, 7: 6,  3: 8, 8: 8,  4: 0, 9: 0}

# 五鼠遁: day_stem -> first hour stem (子时干)
# 甲己之日甲起, 乙庚之日丙起, 丙辛之日戊起, 丁壬之日庚起, 戊癸之日壬起
FIVE_RAT = {0: 0, 5: 0,  1: 2, 6: 2,  2: 4, 7: 4,  3: 6, 8: 6,  4: 8, 9: 8}

# 空亡: each 旬 (10-day block) in the 60-cycle is missing 2 branches
# 旬 index = sixty_cycle_idx // 10
XUN_KONG = {
    0: [10, 11],  # 甲子旬: missing 戌亥
    1: [8, 9],    # 甲戌旬: missing 申酉
    2: [6, 7],    # 甲申旬: missing 午未
    3: [4, 5],    # 甲午旬: missing 辰巳
    4: [2, 3],    # 甲辰旬: missing 寅卯
    5: [0, 1],    # 甲寅旬: missing 子丑
}

# 旬名 for display
XUN_NAMES = ["甲子旬", "甲戌旬", "甲申旬", "甲午旬", "甲辰旬", "甲寅旬"]

# 24 solar terms baseline dates (month, day) for year 2000
# 12 节 (jie) used for month pillar
SOLAR_TERMS = [
    ("立春", 2, 4),   # 0  - jie, month pillar start: 寅
    ("雨水", 2, 19),  # 1  - qi
    ("惊蛰", 3, 5),   # 2  - jie, 卯
    ("春分", 3, 20),  # 3  - qi
    ("清明", 4, 4),   # 4  - jie, 辰
    ("谷雨", 4, 20),  # 5  - qi
    ("立夏", 5, 5),   # 6  - jie, 巳
    ("小满", 5, 21),  # 7  - qi
    ("芒种", 6, 5),   # 8  - jie, 午
    ("夏至", 6, 21),  # 9  - qi
    ("小暑", 7, 7),   # 10 - jie, 未
    ("大暑", 7, 22),  # 11 - qi
    ("立秋", 8, 7),   # 12 - jie, 申
    ("处暑", 8, 23),  # 13 - qi
    ("白露", 9, 7),   # 14 - jie, 酉
    ("秋分", 9, 23),  # 15 - qi
    ("寒露", 10, 8),  # 16 - jie, 戌
    ("霜降", 10, 23), # 17 - qi
    ("立冬", 11, 7),  # 18 - jie, 亥
    ("小雪", 11, 22), # 19 - qi
    ("大雪", 12, 7),  # 20 - jie, 子
    ("冬至", 12, 21), # 21 - qi
    ("小寒", 1, 5),   # 22 - jie, 丑
    ("大寒", 1, 20),  # 23 - qi
]


# ============================================================
# Calculation Functions
# ============================================================

def _compute_solar_term(year: int, n: int, base_month: int, c_pair: tuple[float, float]) -> tuple[date, int, int]:
    """Compute solar term date and approximate time (hour, minute).

    Uses the standard Chinese astronomical formula:
      raw = Y * 0.2422 + C
      D = int(raw) - int(Y / 4)
      time = fractional part of raw (fraction of a day)

    Returns (date, hour, minute). Accuracy: ±30 minutes for 1900-2099.
    """
    if 1900 <= year <= 1999:
        c = c_pair[0]
        y = year - 1900
    elif 2000 <= year <= 2099:
        c = c_pair[1]
        y = year - 2000
    else:
        c = c_pair[1]
        y = year - 2000
        correction = (year - 2000) // 400 * 0.0003 * (year - 2000)
        c += correction

    raw = y * 0.2422 + c
    day_of_month = int(raw) - int(y / 4)

    # Extract time from fractional part
    fraction = raw - int(raw)
    total_minutes = int(fraction * 24 * 60 + 0.5)  # round to nearest minute
    st_hour = total_minutes // 60
    st_minute = total_minutes % 60

    if n >= 22:
        target_year = year + 1
    else:
        target_year = year

    month = base_month

    while True:
        try:
            if month == 2 and day_of_month > 29:
                day_of_month = 29 if _is_leap(target_year) else 28
            return date(target_year, month, day_of_month), st_hour, st_minute
        except ValueError:
            day_of_month -= 1


def _is_leap(year: int) -> bool:
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)


def get_year_pillar_for_date(year: int, month: int, day: int, hour: int = 0, minute: int = 0) -> tuple[int, int]:
    """Compute year pillar (年柱), adjusting for pre-立春 dates.

    Uses precise solar term hour/minute comparison. If birth is on 立春 day
    but before the exact 立春 time, the previous year's pillar applies.
    """
    lichun_date, lichun_h, lichun_m = _compute_solar_term(year, 0, 2, _get_c_values(0))
    birth_date = date(year, month, day)

    if birth_date < lichun_date:
        effective_year = year - 1
    elif birth_date == lichun_date:
        # Same date: compare time (hour, minute)
        birth_minutes = hour * 60 + minute
        lichun_minutes = lichun_h * 60 + lichun_m
        if birth_minutes < lichun_minutes:
            effective_year = year - 1
        else:
            effective_year = year
    else:
        effective_year = year
    return get_year_pillar(effective_year)


def get_year_pillar(year: int) -> tuple[int, int]:
    """Compute year pillar (年柱)."""
    stem_idx = (year - 4) % 10
    branch_idx = (year - 4) % 12
    return stem_idx, branch_idx


def get_day_pillar(year: int, month: int, day: int) -> tuple[int, int]:
    """Compute day pillar (日柱) using days since 1900-01-01 (甲戌日)."""
    ref = date(1900, 1, 1)  # 甲戌日
    birth = date(year, month, day)
    delta = (birth - ref).days
    cycle_idx = (10 + delta) % 60
    stem_idx = cycle_idx % 10
    branch_idx = cycle_idx % 12
    return stem_idx, branch_idx


def get_month_pillar(year: int, month: int, day: int, year_stem_idx: int,
                     hour: int = 0, minute: int = 0) -> tuple[int, int, tuple, tuple]:
    """Compute month pillar (月柱) based on solar terms with precise time comparison.

    Builds a complete list of 节 intervals covering the birth year,
    including the previous year's 小寒 and the next year's 立春.
    Each 节 entry includes (name, date, hour, minute, month_branch_idx).
    """
    birth_date = date(year, month, day)
    birth_minutes = hour * 60 + minute

    # Collect all relevant 节 as (name, date, hour, minute, month_branch_idx)
    jie_list: list[tuple[str, date, int, int, int]] = []

    # Previous year's 大雪
    prev_daxue = _compute_solar_term(year - 1, 20, 12, _get_c_values(20))
    jie_list.append(("大雪", *prev_daxue, 0))  # 子月

    # Previous year's 小寒
    prev_xiaohan = _compute_solar_term(year - 1, 22, 1, _get_c_values(22))
    jie_list.append(("小寒", *prev_xiaohan, 1))  # 丑月

    # This year's 12 jie
    jie_term_indices = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
    jie_month_branches = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1]  # 寅..丑

    for term_idx, mb in zip(jie_term_indices, jie_month_branches):
        dt, h, m = _compute_solar_term(year, term_idx, SOLAR_TERMS[term_idx][1],
                                       _get_c_values(term_idx))
        name = SOLAR_TERMS[term_idx][0]
        jie_list.append((name, dt, h, m, mb))

    # Next year's 立春
    next_lichun = _compute_solar_term(year + 1, 0, 2, _get_c_values(0))
    jie_list.append(("立春", *next_lichun, 2))  # 寅月

    # Find which interval the birth falls in (comparing date + time)
    for i in range(len(jie_list) - 1):
        _, jie_date, jie_h, jie_m, mb_idx = jie_list[i]
        _, next_date, next_h, next_m, _ = jie_list[i + 1]
        jie_minutes = jie_h * 60 + jie_m
        next_minutes = next_h * 60 + next_m

        # Check birth >= jie
        after_start = (birth_date > jie_date or
                       (birth_date == jie_date and birth_minutes >= jie_minutes))
        # Check birth < next_jie
        before_end = (birth_date < next_date or
                      (birth_date == next_date and birth_minutes < next_minutes))

        if after_start and before_end:
            prev_jie = (jie_list[i][0], jie_date, jie_h, jie_m)
            next_jie = (jie_list[i + 1][0], next_date, next_h, next_m)

            # Month stem from 五虎遁
            first_month_stem = FIVE_TIGER[year_stem_idx]
            offset = (mb_idx - 2) % 12
            month_stem_idx = (first_month_stem + offset) % 10
            return month_stem_idx, mb_idx, prev_jie, next_jie

    # Fallback
    first_month_stem = FIVE_TIGER[year_stem_idx]
    return 0, 0, ("未知", birth_date, 0, 0), ("未知", birth_date, 0, 0)


def _get_c_values(term_idx: int) -> tuple[float, float]:
    """Get (20th_century_C, 21st_century_C) for a solar term."""
    C_VALUES = {
        0:  (4.63, 4.73),   1:  (19.46, 19.44),
        2:  (6.42, 6.32),   3:  (21.04, 21.00),
        4:  (5.15, 5.22),   5:  (20.39, 20.42),
        6:  (5.52, 5.94),   7:  (21.04, 21.37),
        8:  (5.68, 6.27),   9:  (21.34, 21.56),
        10: (7.11, 7.49),   11: (22.66, 22.88),
        12: (7.50, 8.05),   13: (23.13, 23.31),
        14: (7.65, 8.24),   15: (23.29, 23.47),
        16: (8.47, 8.86),   17: (23.74, 23.91),
        18: (7.72, 8.27),   19: (22.93, 23.19),
        20: (7.18, 7.77),   21: (21.94, 22.33),
        22: (6.11, 6.05),   23: (20.84, 20.85),
    }
    return C_VALUES.get(term_idx, (0, 0))


def get_hour_pillar(day_stem_idx: int, hour: int, minute: int = 0) -> tuple[int, int]:
    """Compute hour pillar (时柱)."""
    # Determine 时辰 branch
    total_minutes = hour * 60 + minute

    if total_minutes >= 1380 or total_minutes < 60:  # 23:00 - 01:00
        h_branch = 0  # 子
    elif total_minutes < 180:  # 01:00 - 03:00
        h_branch = 1  # 丑
    elif total_minutes < 300:  # 03:00 - 05:00
        h_branch = 2  # 寅
    elif total_minutes < 420:  # 05:00 - 07:00
        h_branch = 3  # 卯
    elif total_minutes < 540:  # 07:00 - 09:00
        h_branch = 4  # 辰
    elif total_minutes < 660:  # 09:00 - 11:00
        h_branch = 5  # 巳
    elif total_minutes < 780:  # 11:00 - 13:00
        h_branch = 6  # 午
    elif total_minutes < 900:  # 13:00 - 15:00
        h_branch = 7  # 未
    elif total_minutes < 1020:  # 15:00 - 17:00
        h_branch = 8  # 申
    elif total_minutes < 1140:  # 17:00 - 19:00
        h_branch = 9  # 酉
    elif total_minutes < 1260:  # 19:00 - 21:00
        h_branch = 10  # 戌
    else:  # 21:00 - 23:00
        h_branch = 11  # 亥

    # Hour stem from 五鼠遁
    first_hour_stem = FIVE_RAT[day_stem_idx]
    h_stem = (first_hour_stem + h_branch) % 10

    return h_stem, h_branch


def get_nayin(stem_idx: int, branch_idx: int) -> str:
    """Get 纳音 for a stem-branch pair."""
    cycle_idx = NAYIN_IDX_MAP.get((stem_idx, branch_idx))
    if cycle_idx is None:
        return "未知"
    return NAYIN[cycle_idx]


def get_ten_god(day_stem_idx: int, other_stem_idx: int) -> str:
    """Compute ten god (十神) name for other_stem relative to day_stem."""
    d_elem = ELEMENTS[day_stem_idx]
    o_elem = ELEMENTS[other_stem_idx]
    same_yy = STEM_YY[day_stem_idx] == STEM_YY[other_stem_idx]

    if day_stem_idx == other_stem_idx:
        return "比肩"

    if d_elem == o_elem:
        return "劫财" if not same_yy else "比肩"

    # day generates other
    if GEN_BY[o_elem] == d_elem:
        return "食神" if same_yy else "伤官"

    # other generates day
    if GEN_BY[d_elem] == o_elem:
        return "偏印" if same_yy else "正印"

    # day controls other
    if CTRL_BY[o_elem] == d_elem:
        return "偏财" if same_yy else "正财"

    # other controls day
    if CTRL_BY[d_elem] == o_elem:
        return "七杀" if same_yy else "正官"

    return "未知"


def get_xunkong(sixty_cycle_idx: int) -> tuple[str, list[str], list[int]]:
    """Compute 空亡 (void branches) for a 60-cycle index.
    Returns (xun_name, void_branches, void_idxs).
    """
    xun_idx = sixty_cycle_idx // 10
    void_idxs = XUN_KONG.get(xun_idx, [])
    xun_name = XUN_NAMES[xun_idx]
    void_branches = [BRANCHES[i] for i in void_idxs]
    return xun_name, void_branches, void_idxs


def get_hidden_stems_info(branch_idx: int) -> list[tuple[int, str]]:
    """Get list of {stem_idx, stem, ten_god, strength} for a branch's hidden stems."""
    return HIDDEN_STEMS.get(branch_idx, [])


def get_minggong(year_stem_idx: int, month_branch_idx: int, hour_branch_idx: int) -> tuple[int, int]:
    """Compute 命宫 (Life Palace) stem and branch.
    命宫地支 = (month_branch - hour_branch - 1) mod 12 (正月起寅, 顺至生月, 逆至生时)
    命宫天干 from 五虎遁 based on year stem.
    """
    mg_branch = (month_branch_idx - hour_branch_idx - 1) % 12
    first_month_stem = FIVE_TIGER[year_stem_idx]
    mg_stem = (first_month_stem + mg_branch - 2) % 10  # 2 = 寅
    return mg_stem, mg_branch


def get_taiyuan(month_stem_idx: int, month_branch_idx: int) -> tuple[int, int]:
    """Compute 胎元 (Fetus Origin) stem and branch.
    胎元 = month stem + 1, month branch + 3.
    """
    ty_stem = (month_stem_idx + 1) % 10
    ty_branch = (month_branch_idx + 3) % 12
    return ty_stem, ty_branch


def get_dayun(year_stem_idx: int, month_stem_idx: int, month_branch_idx: int,
              birth_date: date, prev_jie_date: date, next_jie_date: date, gender: str) -> tuple[list[dict], int, int]:
    """Compute major luck cycles (大运)."""
    # Normalize gender (handle Chinese characters)
    g = str(gender).lower()
    if g == "男":
        g = "male"
    elif g == "女":
        g = "female"
    year_is_yang = STEM_YY[year_stem_idx] == "阳"
    is_male = g == "male"

    go_forward = (year_is_yang and is_male) or (not year_is_yang and not is_male)

    # Calculate starting age
    if go_forward:
        target_date = next_jie_date
    else:
        target_date = prev_jie_date

    days_diff = abs((birth_date - target_date).days)
    start_age = round(days_diff / 3.0)

    dayun_list = []
    for i in range(8):
        age = start_age + i * 10
        if go_forward:
            dy_stem = (month_stem_idx + 1 + i) % 10
            dy_branch = (month_branch_idx + 1 + i) % 12
            direction = "顺排"
        else:
            dy_stem = (month_stem_idx - 1 - i) % 10
            dy_branch = (month_branch_idx - 1 - i) % 12
            direction = "逆排"

        dayun_list.append({
            "start_age": age,
            "stem": STEMS[dy_stem],
            "stem_idx": dy_stem,
            "branch": BRANCHES[dy_branch],
            "branch_idx": dy_branch,
            "nayin": get_nayin(dy_stem, dy_branch),
            "direction": direction,
        })

    return dayun_list, start_age, days_diff


def get_shensha(pillars: list[tuple[str, int, int]], day_stem_idx: int, year_stem_idx: int, year_branch_idx: int) -> dict[str, list[str]]:
    """Compute spirit stars (神煞) for each pillar."""
    # Extract month branch from pillars
    month_branch_idx = None
    for pname, s_idx, b_idx in pillars:
        if pname == "month":
            month_branch_idx = b_idx
            break

    # 天乙贵人: based on day stem (also year stem)
    TIANYI_MAP = {
        0: [1, 7], 4: [1, 7], 6: [1, 7],  # 甲戊庚 → 丑未
        1: [0, 8], 5: [0, 8],             # 乙己 → 子申
        2: [11, 9], 3: [11, 9],           # 丙丁 → 亥酉
        7: [6, 2],                         # 辛 → 午寅
        8: [5, 3], 9: [5, 3],             # 壬癸 → 巳卯
    }

    # 文昌: based on day stem
    WENCHANG_MAP = {
        0: 5, 1: 6, 2: 8, 3: 9, 4: 8,
        5: 9, 6: 11, 7: 0, 8: 2, 9: 3,
    }

    # 太极贵人: based on day stem
    TAIJI_MAP = {
        0: [0, 6], 5: [0, 6],   # 甲己 → 子午
        1: [1, 7], 6: [1, 7],   # 乙庚 → 丑未
        2: [2, 8], 7: [2, 8],   # 丙辛 → 寅申
        3: [3, 9], 8: [3, 9],   # 丁壬 → 卯酉
        4: [4, 10], 9: [4, 10], # 戊癸 → 辰戌
    }

    # 天德贵人: based on month branch (some check stem, some check branch)
    TIANDE_MAP = {
        2: ('stem', 3),    # 寅月 → 丁
        3: ('branch', 8),  # 卯月 → 申
        4: ('stem', 8),    # 辰月 → 壬
        5: ('stem', 7),    # 巳月 → 辛
        6: ('branch', 11), # 午月 → 亥
        7: ('stem', 0),    # 未月 → 甲
        8: ('stem', 9),    # 申月 → 癸
        9: ('branch', 2),  # 酉月 → 寅
        10: ('stem', 2),   # 戌月 → 丙
        11: ('stem', 1),   # 亥月 → 乙
        0: ('branch', 5),  # 子月 → 巳
        1: ('stem', 6),    # 丑月 → 庚
    }

    # 月德贵人: based on month branch, check stem
    YUEDE_MAP = {
        2: 2, 6: 2, 10: 2,   # 寅午戌 → 丙
        8: 8, 0: 8, 4: 8,    # 申子辰 → 壬
        11: 0, 3: 0, 7: 0,   # 亥卯未 → 甲
        5: 6, 9: 6, 1: 6,    # 巳酉丑 → 庚
    }

    # 金舆: based on day stem
    JINYU_MAP = {
        0: 4,         # 甲 → 辰
        1: 5,         # 乙 → 巳
        2: 7, 4: 7,   # 丙戊 → 未
        3: 8, 5: 8,   # 丁己 → 申
        6: 10,        # 庚 → 戌
        7: 11,        # 辛 → 亥
        8: 1,         # 壬 → 丑
        9: 2,         # 癸 → 寅
    }

    # 禄神: based on day stem
    LUSHEN_MAP = {0: 2, 1: 3, 2: 5, 3: 6, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 0}

    # 羊刃: based on day stem
    YANGREN_MAP = {0: 3, 1: 2, 2: 6, 3: 5, 4: 6, 5: 5, 6: 9, 7: 8, 8: 0, 9: 11}

    # ---- Below: based on year branch (三合局 groups) ----

    # 桃花 (咸池)
    TAOHUA_MAP = {
        2: 3, 6: 3, 10: 3,  # 寅午戌 → 卯
        8: 9, 0: 9, 4: 9,   # 申子辰 → 酉
        5: 6, 9: 6, 1: 6,   # 巳酉丑 → 午
        11: 0, 3: 0, 7: 0,  # 亥卯未 → 子
    }

    # 驿马
    YIMA_MAP = {
        2: 8, 6: 8, 10: 8,   # 寅午戌 → 申
        8: 2, 0: 2, 4: 2,    # 申子辰 → 寅
        5: 11, 9: 11, 1: 11, # 巳酉丑 → 亥
        11: 5, 3: 5, 7: 5,   # 亥卯未 → 巳
    }

    # 华盖
    HUAGAI_MAP = {
        2: 10, 6: 10, 10: 10, # 寅午戌 → 戌
        8: 4, 0: 4, 4: 4,     # 申子辰 → 辰
        5: 1, 9: 1, 1: 1,     # 巳酉丑 → 丑
        11: 7, 3: 7, 7: 7,    # 亥卯未 → 未
    }

    # 将星
    JIANGXING_MAP = {
        2: 6, 6: 6, 10: 6,  # 寅午戌 → 午
        8: 0, 0: 0, 4: 0,   # 申子辰 → 子
        5: 9, 9: 9, 1: 9,   # 巳酉丑 → 酉
        11: 3, 3: 3, 7: 3,  # 亥卯未 → 卯
    }

    # 劫煞
    JIESHA_MAP = {
        2: 11, 6: 11, 10: 11,  # 寅午戌 → 亥
        8: 5, 0: 5, 4: 5,      # 申子辰 → 巳
        5: 2, 9: 2, 1: 2,      # 巳酉丑 → 寅
        11: 8, 3: 8, 7: 8,     # 亥卯未 → 申
    }

    # 灾煞
    ZAISHA_MAP = {
        2: 0, 6: 0, 10: 0,   # 寅午戌 → 子
        8: 6, 0: 6, 4: 6,    # 申子辰 → 午
        5: 3, 9: 3, 1: 3,    # 巳酉丑 → 卯
        11: 9, 3: 9, 7: 9,   # 亥卯未 → 酉
    }

    # 亡神
    WANGSHEN_MAP = {
        2: 5, 6: 5, 10: 5,   # 寅午戌 → 巳
        8: 11, 0: 11, 4: 11,  # 申子辰 → 亥
        5: 8, 9: 8, 1: 8,    # 巳酉丑 → 申
        11: 2, 3: 2, 7: 2,   # 亥卯未 → 寅
    }

    tianyi_branches = set(TIANYI_MAP.get(day_stem_idx, []))
    tianyi_branches |= set(TIANYI_MAP.get(year_stem_idx, []))
    wenchang_branch = WENCHANG_MAP.get(day_stem_idx)
    taiji_branches = set(TAIJI_MAP.get(day_stem_idx, []))
    jinyu_branch = JINYU_MAP.get(day_stem_idx)
    lushen_branch = LUSHEN_MAP.get(day_stem_idx)
    yangren_branch = YANGREN_MAP.get(day_stem_idx)

    taohua_branch = TAOHUA_MAP.get(year_branch_idx)
    yima_branch = YIMA_MAP.get(year_branch_idx)
    huagai_branch = HUAGAI_MAP.get(year_branch_idx)
    jiangxing_branch = JIANGXING_MAP.get(year_branch_idx)
    jiesha_branch = JIESHA_MAP.get(year_branch_idx)
    zaisha_branch = ZAISHA_MAP.get(year_branch_idx)
    wangshen_branch = WANGSHEN_MAP.get(year_branch_idx)

    tiande_info = TIANDE_MAP.get(month_branch_idx) if month_branch_idx is not None else None
    yuede_stem = YUEDE_MAP.get(month_branch_idx) if month_branch_idx is not None else None

    shensha = {}
    for pillar_name, s_idx, b_idx in pillars:
        stars = []
        # Stem-based
        if b_idx in tianyi_branches:
            stars.append("天乙贵人")
        if b_idx == wenchang_branch:
            stars.append("文昌")
        if b_idx in taiji_branches:
            stars.append("太极贵人")
        if b_idx == jinyu_branch:
            stars.append("金舆")
        if b_idx == lushen_branch:
            stars.append("禄神")
        if b_idx == yangren_branch:
            stars.append("羊刃")
        # Year-branch-based
        if b_idx == taohua_branch:
            stars.append("桃花")
        if b_idx == yima_branch:
            stars.append("驿马")
        if b_idx == huagai_branch:
            stars.append("华盖")
        if b_idx == jiangxing_branch:
            stars.append("将星")
        if b_idx == jiesha_branch:
            stars.append("劫煞")
        if b_idx == zaisha_branch:
            stars.append("灾煞")
        if b_idx == wangshen_branch:
            stars.append("亡神")
        # 天德贵人: check type (stem or branch) by month
        if tiande_info is not None:
            check_type, check_val = tiande_info
            if (check_type == 'stem' and s_idx == check_val) or \
               (check_type == 'branch' and b_idx == check_val):
                stars.append("天德贵人")
        # 月德贵人: check stem by month
        if yuede_stem is not None and s_idx == yuede_stem:
            stars.append("月德贵人")

        shensha[pillar_name] = stars

    return shensha


def get_wuxing_counts(day_stem_idx: int, pillars_data: list[tuple[str, int, int]]) -> dict[str, int]:
    """Count five elements across all pillars (stems + branches)."""
    counts = {"木": 0, "火": 0, "土": 0, "金": 0, "水": 0}

    # Day stem
    counts[ELEMENTS[day_stem_idx]] += 1

    # Each pillar stem and branch
    for pname, s_idx, b_idx in pillars_data:
        counts[ELEMENTS[s_idx]] += 1
        counts[BRANCH_ELEMENTS[b_idx]] += 1

    return counts


def format_chart_output(year: int, month: int, day: int, hour: int, minute: int, gender: str) -> dict:
    """Main calculation and formatting function."""
    y_s, y_b = get_year_pillar_for_date(year, month, day, hour, minute)
    d_s, d_b = get_day_pillar(year, month, day)
    m_s, m_b, prev_jie, next_jie = get_month_pillar(year, month, day, y_s, hour, minute)
    h_s, h_b = get_hour_pillar(d_s, hour, minute)
    birth_date = date(year, month, day)

    pillars = [
        ("year", y_s, y_b),
        ("month", m_s, m_b),
        ("day", d_s, d_b),
        ("hour", h_s, h_b),
    ]

    # Hidden stems for each branch
    hidden_info = {}
    for pname, s_idx, b_idx in pillars:
        hs_list = get_hidden_stems_info(b_idx)
        hidden_info[pname] = [
            {"stem": STEMS[hs[0]], "stem_idx": hs[0], "ten_god": get_ten_god(d_s, hs[0]),
             "strength": hs[1]}
            for hs in hs_list
        ]

    # Ten gods for stems and branch本气
    ten_gods = {}
    for pname, s_idx, b_idx in pillars:
        main_hidden = get_hidden_stems_info(b_idx)[0][0] if get_hidden_stems_info(b_idx) else b_idx
        ten_gods[pname] = {
            "stem_tg": get_ten_god(d_s, s_idx),
            "branch_tg": get_ten_god(d_s, main_hidden),
            "branch_tg_stem": STEMS[main_hidden],
        }

    # Five elements
    five_elems = {}
    for pname, s_idx, b_idx in pillars:
        five_elems[pname] = {
            "stem": ELEMENTS[s_idx],
            "branch": BRANCH_ELEMENTS[b_idx],
        }

    # Na Yin
    nayins = {}
    for pname, s_idx, b_idx in pillars:
        nayins[pname] = get_nayin(s_idx, b_idx)

    # Wuxing counts
    wuxing_counts = get_wuxing_counts(d_s, pillars)

    # Major luck
    prev_jie_date = prev_jie[1]
    next_jie_date = next_jie[1]
    dayun, start_age_rounded, start_age_days = get_dayun(
        y_s, m_s, m_b, birth_date, prev_jie_date, next_jie_date, gender)

    # Shensha
    shensha = get_shensha(pillars, d_s, y_s, y_b)

    # Current year liunian (current year ± 1)
    current_year = date.today().year
    liunian_list = []
    for yr in [current_year - 1, current_year, current_year + 1]:
        ln_s, ln_b = get_year_pillar(yr)
        ln_cycle = NAYIN_IDX_MAP.get((ln_s, ln_b), -1)
        liunian_list.append({
            "year": yr,
            "stem": STEMS[ln_s],
            "stem_idx": ln_s,
            "branch": BRANCHES[ln_b],
            "branch_idx": ln_b,
            "nayin": NAYIN[ln_cycle] if ln_cycle >= 0 else "未知",
            "ten_god": get_ten_god(d_s, ln_s),
            "sixty_cycle_idx": ln_cycle,
        })

    # 命宫 and 胎元
    mg_s, mg_b = get_minggong(y_s, m_b, h_b)
    ty_s, ty_b = get_taiyuan(m_s, m_b)
    minggong = {
        "stem": STEMS[mg_s], "stem_idx": mg_s,
        "branch": BRANCHES[mg_b], "branch_idx": mg_b,
        "nayin": get_nayin(mg_s, mg_b),
        "ten_god": get_ten_god(d_s, mg_s),
    }
    taiyuan = {
        "stem": STEMS[ty_s], "stem_idx": ty_s,
        "branch": BRANCHES[ty_b], "branch_idx": ty_b,
        "nayin": get_nayin(ty_s, ty_b),
        "ten_god": get_ten_god(d_s, ty_s),
    }

    return {
        "birth": {
            "year": year, "month": month, "day": day,
            "hour": hour, "minute": minute, "gender": gender,
            "shichen": BRANCHES[h_b] + "时",
        },
        "pillars": {
            "year": {"stem": STEMS[y_s], "stem_idx": y_s, "branch": BRANCHES[y_b],
                     "branch_idx": y_b, "nayin": nayins["year"],
                     "xunkong": (y_xk := get_xunkong(NAYIN_IDX_MAP.get((y_s, y_b), 0))),
                     "is_xunkong": y_b in y_xk[2]},
            "month": {"stem": STEMS[m_s], "stem_idx": m_s, "branch": BRANCHES[m_b],
                      "branch_idx": m_b, "nayin": nayins["month"],
                      "xunkong": (m_xk := get_xunkong(NAYIN_IDX_MAP.get((m_s, m_b), 0))),
                      "is_xunkong": m_b in m_xk[2]},
            "day": {"stem": STEMS[d_s], "stem_idx": d_s, "branch": BRANCHES[d_b],
                    "branch_idx": d_b, "nayin": nayins["day"],
                    "xunkong": (d_xk := get_xunkong(NAYIN_IDX_MAP.get((d_s, d_b), 0))),
                    "is_xunkong": d_b in d_xk[2]},
            "hour": {"stem": STEMS[h_s], "stem_idx": h_s, "branch": BRANCHES[h_b],
                     "branch_idx": h_b, "nayin": nayins["hour"],
                     "xunkong": (h_xk := get_xunkong(NAYIN_IDX_MAP.get((h_s, h_b), 0))),
                     "is_xunkong": h_b in h_xk[2]},
        },
        "day_master": {
            "stem": STEMS[d_s], "stem_idx": d_s,
            "element": ELEMENTS[d_s], "yin_yang": STEM_YY[d_s],
        },
        "ten_gods": ten_gods,
        "five_elements": five_elems,
        "hidden_stems": hidden_info,
        "wuxing_counts": wuxing_counts,
        "dayun": dayun,
        "start_age": start_age_rounded,
        "start_age_days": start_age_days,
        "shensha": shensha,
        "solar_terms": {
            "prev_jie": prev_jie[0],
            "next_jie": next_jie[0],
            "prev_jie_date": str(prev_jie_date),
            "next_jie_date": str(next_jie_date),
            "prev_jie_time": f"{prev_jie[2]:02d}:{prev_jie[3]:02d}",
            "next_jie_time": f"{next_jie[2]:02d}:{next_jie[3]:02d}",
        },
        "sixty_cycle_idx": {
            "year": NAYIN_IDX_MAP.get((y_s, y_b), -1),
            "month": NAYIN_IDX_MAP.get((m_s, m_b), -1),
            "day": NAYIN_IDX_MAP.get((d_s, d_b), -1),
            "hour": NAYIN_IDX_MAP.get((h_s, h_b), -1),
        },
        "boundary_warning": _check_boundary(birth_date, prev_jie, next_jie),
        "liunian": liunian_list,
        "minggong": minggong,
        "taiyuan": taiyuan,
    }


def _check_boundary(birth_date: date, prev_jie: tuple, next_jie: tuple) -> Optional[str]:
    """Check if birth is near a solar term boundary (within 1 day).

    Since we now compare exact hour/minute against the solar term time,
    same-day births are correctly assigned. The warning is for verification.
    """
    prev_jie_date = prev_jie[1]
    next_jie_date = next_jie[1]
    prev_diff = abs((birth_date - prev_jie_date).days)
    next_diff = abs((birth_date - next_jie_date).days)

    if prev_diff <= 1 or next_diff <= 1:
        jie_name = next_jie[0] if next_diff <= prev_diff else prev_jie[0]
        jie_time = f"{next_jie[2]:02d}:{next_jie[3]:02d}" if next_diff <= prev_diff else f"{prev_jie[2]:02d}:{prev_jie[3]:02d}"
        return ("出生日期接近「{}」节气交界（{}天，节气时刻约 {}），月柱已按精确时辰计算，"
                "建议核实。".format(jie_name, min(prev_diff, next_diff), jie_time))
    return None


# ============================================================
# Main Entry Point
# ============================================================

def _read_json_input(raw: str) -> dict:
    """Parse JSON input, stripping any UTF-8 BOM."""
    raw = raw.strip()
    # Strip BOM if present (common on Windows / PowerShell)
    if raw.startswith('﻿'):
        raw = raw[1:]
    if not raw:
        raise ValueError("No input provided")
    return json.loads(raw)


def main() -> None:
    """Main entry point. Supports CLI flags, positional args, and stdin JSON.

    CLI flags:  python bazi_calculator.py --year 1990 --month 6 --day 15 --hour 12 [--minute 0] [--gender male]
    Positional: python bazi_calculator.py 1990 6 15 12 [0] [male]
    Stdin:      echo '{"year":1990,...}' | python bazi_calculator.py
    File:       python bazi_calculator.py --file input.json
    """

    parser = argparse.ArgumentParser(
        description="Ba Zi (Four Pillars of Destiny) calculator",
        epilog="Without flags, reads JSON from stdin. "
               "With positional numeric args: <year> <month> <day> <hour> [minute] [gender].",
    )
    parser.add_argument("--year",   "-y", type=int, help="Birth year (e.g. 1990)")
    parser.add_argument("--month",  "-m", type=int, help="Birth month (1-12)")
    parser.add_argument("--day",    "-d", type=int, help="Birth day (1-31)")
    parser.add_argument("--hour",   "-H", type=int, help="Birth hour (0-23)")
    parser.add_argument("--minute", "-M", type=int, default=0, help="Birth minute (0-59, default 0)")
    parser.add_argument("--gender", "-g", type=str, default="male",
                        help="Gender: male/female or 男/女 (default male)")
    parser.add_argument("--file",   "-f", type=str, help="Read JSON input from file")

    # Also accept positional args for backward compatibility
    parser.add_argument("positional", nargs="*", help=argparse.SUPPRESS)

    args = parser.parse_args()

    # Determine input mode
    if args.year is not None:
        # Named-flag mode
        year = args.year
        month = args.month
        day = args.day
        hour = args.hour
        minute = args.minute
        gender_raw = args.gender

        # Validate required fields in flag mode
        if month is None or day is None or hour is None:
            parser.error("--year, --month, --day, --hour are all required in flag mode")
    elif args.file:
        # File input mode
        try:
            with open(args.file, 'r', encoding='utf-8-sig') as f:
                raw = f.read()
        except FileNotFoundError:
            print(json.dumps({"error": f"File not found: {args.file}"}, ensure_ascii=False))
            sys.exit(1)
        except OSError as e:
            print(json.dumps({"error": f"Cannot read file: {e}"}, ensure_ascii=False))
            sys.exit(1)
        try:
            data = _read_json_input(raw)
        except (json.JSONDecodeError, ValueError) as e:
            print(json.dumps({"error": f"Invalid JSON in file: {e}"}, ensure_ascii=False))
            sys.exit(1)
        return _from_data(data)
    elif args.positional and args.positional[0].isdigit():
        # Positional-arg mode (backward compat)
        try:
            pos = args.positional
            year = int(pos[0])
            month = int(pos[1])
            day = int(pos[2])
            hour = int(pos[3])
            minute = int(pos[4]) if len(pos) > 4 and pos[4].isdigit() else 0
            gender_raw = pos[5] if len(pos) > 5 else "male"
        except (IndexError, ValueError):
            print(json.dumps(
                {"error": "Usage: python bazi_calculator.py <year> <month> <day> <hour> [minute] [gender]"},
                ensure_ascii=False))
            sys.exit(1)
    else:
        # Stdin JSON mode — read binary, then decode to handle BOM
        raw_bytes = sys.stdin.buffer.read()
        raw = raw_bytes.decode('utf-8-sig')
        try:
            data = _read_json_input(raw)
        except (json.JSONDecodeError, ValueError) as e:
            print(json.dumps({"error": f"Invalid JSON: {e}"}, ensure_ascii=False))
            sys.exit(1)
        return _from_data(data)

    # Normalize gender
    gender = gender_raw.lower()
    if gender not in ("male", "female", "男", "女"):
        gender = "male"
    if gender == "男":
        gender = "male"
    elif gender == "女":
        gender = "female"

    # Validate date
    try:
        date(year, month, day)
    except ValueError as e:
        print(json.dumps({"error": f"Invalid date: {e}"}, ensure_ascii=False))
        sys.exit(1)

    result = format_chart_output(year, month, day, hour, minute, gender)
    print(json.dumps(result, ensure_ascii=False, indent=2))


def _from_data(data: dict) -> None:
    """Process chart from already-parsed JSON data dict."""
    required = ["year", "month", "day", "hour", "gender"]
    missing = [k for k in required if k not in data]
    if missing:
        print(json.dumps(
            {"error": f"Missing required fields: {', '.join(missing)}"},
            ensure_ascii=False))
        sys.exit(1)

    year = int(data["year"])
    month = int(data["month"])
    day = int(data["day"])
    hour = int(data["hour"])
    minute = int(data.get("minute", 0))
    gender_raw = str(data["gender"]).lower()

    gender = gender_raw
    if gender not in ("male", "female", "男", "女"):
        gender = "male"
    if gender == "男":
        gender = "male"
    elif gender == "女":
        gender = "female"

    try:
        date(year, month, day)
    except ValueError as e:
        print(json.dumps({"error": f"Invalid date: {e}"}, ensure_ascii=False))
        sys.exit(1)

    result = format_chart_output(year, month, day, hour, minute, gender)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
