#!/usr/bin/env python3
"""Ba Zi (Four Pillars of Destiny) calculator.
Pure Python stdlib. Reads JSON from stdin, writes JSON to stdout.
"""

import json
import sys
from datetime import date, timedelta

# ============================================================
# Data Tables
# ============================================================

STEMS = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
BRANCHES = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]
ELEMENTS = ["木", "木", "火", "火", "土", "土", "金", "金", "水", "水"]
STEM_YY = ["阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴"]  # yin/yang
BRANCH_YY = ["阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴", "阳", "阴"]

# 五行相生相克
GEN_BY = {  # generated by: key is generated by value
    "木": "水", "火": "木", "土": "火", "金": "土", "水": "金"
}
CTRL_BY = {  # controlled by: key is controlled by value
    "木": "金", "火": "水", "土": "木", "金": "火", "水": "土"
}

# 纳音 - 60 entries (each pair shares one name, so 30 unique names x2)
NAYIN = [
    "海中金", "海中金", "炉中火", "炉中火", "大林木", "大林木",
    "路旁土", "路旁土", "剑锋金", "剑锋金", "山头火", "山头火",
    "涧下水", "涧下水", "城头土", "城头土", "白蜡金", "白蜡金",
    "杨柳木", "杨柳木", "泉中水", "泉中水", "屋上土", "屋上土",
    "霹雳火", "霹雳火", "松柏木", "松柏木", "长流水", "长流水",
    "沙中金", "沙中金", "山下火", "山下火", "平地木", "平地木",
    "壁上土", "壁上土", "金箔金", "金箔金", "覆灯火", "覆灯火",
    "天河水", "天河水", "大驿土", "大驿土", "钗钏金", "钗钏金",
    "桑柘木", "桑柘木", "大溪水", "大溪水", "沙中土", "沙中土",
    "天上火", "天上火", "石榴木", "石榴木", "大海水", "大海水",
]

# 地支藏干 (hidden stems in each branch) - list of (stem_idx, strength)
# Strength: 本气, 中气, 余气
HIDDEN_STEMS = {
    0: [(9, "本气")],                          # 子: 癸
    1: [(5, "本气"), (9, "中气"), (7, "余气")],  # 丑: 己癸辛
    2: [(0, "本气"), (2, "中气"), (4, "余气")],  # 寅: 甲丙戊
    3: [(1, "本气")],                          # 卯: 乙
    4: [(4, "本气"), (1, "中气"), (9, "余气")],  # 辰: 戊乙癸
    5: [(2, "本气"), (6, "中气"), (4, "余气")],  # 巳: 丙庚戊
    6: [(3, "本气"), (5, "中气")],              # 午: 丁己
    7: [(5, "本气"), (3, "中气"), (1, "余气")],  # 未: 己丁乙
    8: [(6, "本气"), (8, "中气"), (4, "余气")],  # 申: 庚壬戊
    9: [(7, "本气")],                          # 酉: 辛
    10: [(4, "本气"), (7, "中气"), (3, "余气")], # 戌: 戊辛丁
    11: [(8, "本气"), (0, "中气")],             # 亥: 壬甲
}

# 60-cycle index map: (stem_idx, branch_idx) -> cycle_idx (0-59)
NAYIN_IDX_MAP = {}
for i in range(60):
    s = i % 10
    b = i % 12
    NAYIN_IDX_MAP[(s, b)] = i

# 五虎遁: year_stem -> first month stem (寅月干)
# 甲己之年丙作首, 乙庚之年戊为头, 丙辛之年庚起, 丁壬之年壬起, 戊癸之年甲起
FIVE_TIGER = {0: 2, 5: 2,  1: 4, 6: 4,  2: 6, 7: 6,  3: 8, 8: 8,  4: 0, 9: 0}

# 五鼠遁: day_stem -> first hour stem (子时干)
# 甲己之日甲起, 乙庚之日丙起, 丙辛之日戊起, 丁壬之日庚起, 戊癸之日壬起
FIVE_RAT = {0: 0, 5: 0,  1: 2, 6: 2,  2: 4, 7: 4,  3: 6, 8: 6,  4: 8, 9: 8}

# 24 solar terms baseline dates (month, day) for year 2000
# 12 节 (jie) used for month pillar
SOLAR_TERMS = [
    ("立春", 2, 4),   # 0  - jie, month pillar start: 寅
    ("雨水", 2, 19),  # 1  - qi
    ("惊蛰", 3, 5),   # 2  - jie, 卯
    ("春分", 3, 20),  # 3  - qi
    ("清明", 4, 4),   # 4  - jie, 辰
    ("谷雨", 4, 20),  # 5  - qi
    ("立夏", 5, 5),   # 6  - jie, 巳
    ("小满", 5, 21),  # 7  - qi
    ("芒种", 6, 5),   # 8  - jie, 午
    ("夏至", 6, 21),  # 9  - qi
    ("小暑", 7, 7),   # 10 - jie, 未
    ("大暑", 7, 22),  # 11 - qi
    ("立秋", 8, 7),   # 12 - jie, 申
    ("处暑", 8, 23),  # 13 - qi
    ("白露", 9, 7),   # 14 - jie, 酉
    ("秋分", 9, 23),  # 15 - qi
    ("寒露", 10, 8),  # 16 - jie, 戌
    ("霜降", 10, 23), # 17 - qi
    ("立冬", 11, 7),  # 18 - jie, 亥
    ("小雪", 11, 22), # 19 - qi
    ("大雪", 12, 7),  # 20 - jie, 子
    ("冬至", 12, 21), # 21 - qi
    ("小寒", 1, 5),   # 22 - jie, 丑
    ("大寒", 1, 20),  # 23 - qi
]

# Month branch for each 节 (indices 0,2,4,6,8,10,12,14,16,18,20,22)
JIE_TO_MONTH_BRANCH = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1]
# Maps to: 寅卯辰巳午未申酉戌亥子丑

# ============================================================
# Calculation Functions
# ============================================================

def get_solar_term_dates(year):
    """Compute all 24 solar term dates for the given year.

    Uses the standard Chinese astronomical formula:
      D = int(Y * 0.2422 + C) - int(Y / 4)
    where Y = last 2 digits of year, C = century+term constant.
    Accuracy: exact date for 1900-2099.
    """
    # C values: [20th_century, 21st_century]
    C_VALUES = {
        0:  (4.63, 4.73),   1:  (19.46, 19.44),   # 立春, 雨水
        2:  (6.42, 6.32),   3:  (21.04, 21.00),   # 惊蛰, 春分
        4:  (5.15, 5.22),   5:  (20.39, 20.42),   # 清明, 谷雨
        6:  (5.52, 5.94),   7:  (21.04, 21.37),   # 立夏, 小满
        8:  (5.68, 6.27),   9:  (21.34, 21.56),   # 芒种, 夏至
        10: (7.11, 7.49),   11: (22.66, 22.88),   # 小暑, 大暑
        12: (7.50, 8.05),   13: (23.13, 23.31),   # 立秋, 处暑
        14: (7.65, 8.24),   15: (23.29, 23.47),   # 白露, 秋分
        16: (8.47, 8.86),   17: (23.74, 23.91),   # 寒露, 霜降
        18: (7.72, 8.27),   19: (22.93, 23.19),   # 立冬, 小雪
        20: (7.18, 7.77),   21: (21.94, 22.33),   # 大雪, 冬至
        22: (6.11, 6.05),   23: (20.84, 20.85),   # 小寒, 大寒
    }

    results = []
    for n in range(24):
        name, ref_month, _ = SOLAR_TERMS[n]
        dt = _compute_solar_term(year, n, ref_month, C_VALUES[n])
        results.append((name, dt))
    return results


def _compute_solar_term(year, n, base_month, c_pair):
    """Compute solar term date using the standard formula."""
    if 1900 <= year <= 1999:
        c = c_pair[0]
        y = year - 1900
    elif 2000 <= year <= 2099:
        c = c_pair[1]
        y = year - 2000
    else:
        # For years outside 1900-2099, use 21st century values + mean longitude correction
        c = c_pair[1]
        y = year - 2000
        # Apply approximate correction for distant years
        correction = (year - 2000) // 400 * 0.0003 * (year - 2000)
        c += correction

    # Standard formula
    day_of_month = int(y * 0.2422 + c) - int(y / 4)

    # Adjust month for terms 小寒/大寒 (n=22,23) which are in the NEXT year's January
    if n >= 22:
        target_year = year + 1
    else:
        target_year = year

    # For terms where base_month is January but we're computing for "this year",
    # the term is in January of the NEXT year
    month = base_month

    # Handle year boundary: for 小寒 and 大寒 (n=22,23),
    # the computed day is in January of year+1
    if n >= 22:
        target_year = year + 1

    # Ensure valid date
    while True:
        try:
            if month == 2 and day_of_month > 29:
                day_of_month = 29 if _is_leap(target_year) else 28
            return date(target_year, month, day_of_month)
        except ValueError:
            day_of_month -= 1


def _is_leap(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)


def get_year_pillar_for_date(year, month, day):
    """Compute year pillar (年柱), adjusting for pre-立春 dates."""
    # Check if the date is before 立春
    lichun = _compute_solar_term(year, 0, 2, (4.63, 4.73))  # 立春
    birth = date(year, month, day)
    if birth < lichun:
        effective_year = year - 1
    else:
        effective_year = year
    return get_year_pillar(effective_year)


def get_year_pillar(year):
    """Compute year pillar (年柱)."""
    stem_idx = (year - 4) % 10
    branch_idx = (year - 4) % 12
    return stem_idx, branch_idx


def get_day_pillar(year, month, day):
    """Compute day pillar (日柱) using days since 1900-01-01 (甲戌日)."""
    ref = date(1900, 1, 1)  # 甲戌日
    birth = date(year, month, day)
    delta = (birth - ref).days
    cycle_idx = (10 + delta) % 60
    stem_idx = cycle_idx % 10
    branch_idx = cycle_idx % 12
    return stem_idx, branch_idx


def get_month_pillar(year, month, day, year_stem_idx):
    """Compute month pillar (月柱) based on solar terms.

    Builds a complete list of 节 intervals covering the birth year,
    including the previous year's 小寒 and the next year's 立春.
    """
    birth = date(year, month, day)

    # Collect all relevant 节: previous year's 大雪 & 小寒, this year's 12 节, next year's 立春
    jie_list = []  # (name, date, month_branch_idx)

    # Previous year's 大雪 (for dates in December of year-1 that fall before 小寒 in Jan of birth year)
    prev_daxue = _compute_solar_term(year - 1, 20, 12, _get_c_values(20))
    jie_list.append(("大雪", prev_daxue, 0))  # 子月

    # Previous year's 小寒 (could be in Jan of birth year)
    prev_xiaohan = _compute_solar_term(year - 1, 22, 1, _get_c_values(22))
    jie_list.append(("小寒", prev_xiaohan, 1))  # 丑月

    # This year's 12 jie (indices: 0=立春, 2=惊蛰, 4=清明, ..., 20=大雪)
    jie_term_indices = [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]
    jie_month_branches = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1]  # 寅..丑

    for term_idx, mb in zip(jie_term_indices, jie_month_branches):
        dt = _compute_solar_term(year, term_idx, SOLAR_TERMS[term_idx][1],
                                 _get_c_values(term_idx))
        name = SOLAR_TERMS[term_idx][0]
        jie_list.append((name, dt, mb))

    # Next year's 立春 (for dates after this year's 小寒)
    next_lichun = _compute_solar_term(year + 1, 0, 2, _get_c_values(0))
    jie_list.append(("立春", next_lichun, 2))  # 寅月

    # Find which interval the birth date falls in
    for i in range(len(jie_list) - 1):
        jie_date = jie_list[i][1]
        next_jie_date = jie_list[i + 1][1]
        if birth >= jie_date and birth < next_jie_date:
            month_branch_idx = jie_list[i][2]
            prev_jie = (jie_list[i][0], jie_date)
            next_jie = (jie_list[i + 1][0], next_jie_date)

            # Month stem from 五虎遁
            first_month_stem = FIVE_TIGER[year_stem_idx]
            offset = (month_branch_idx - 2) % 12  # offset from 寅
            month_stem_idx = (first_month_stem + offset) % 10
            return month_stem_idx, month_branch_idx, prev_jie, next_jie

    # Fallback (shouldn't reach here)
    first_month_stem = FIVE_TIGER[year_stem_idx]
    return 0, 0, ("未知", birth), ("未知", birth)


def _get_c_values(term_idx):
    """Get (20th_century_C, 21st_century_C) for a solar term."""
    C_VALUES = {
        0:  (4.63, 4.73),   1:  (19.46, 19.44),
        2:  (6.42, 6.32),   3:  (21.04, 21.00),
        4:  (5.15, 5.22),   5:  (20.39, 20.42),
        6:  (5.52, 5.94),   7:  (21.04, 21.37),
        8:  (5.68, 6.27),   9:  (21.34, 21.56),
        10: (7.11, 7.49),   11: (22.66, 22.88),
        12: (7.50, 8.05),   13: (23.13, 23.31),
        14: (7.65, 8.24),   15: (23.29, 23.47),
        16: (8.47, 8.86),   17: (23.74, 23.91),
        18: (7.72, 8.27),   19: (22.93, 23.19),
        20: (7.18, 7.77),   21: (21.94, 22.33),
        22: (6.11, 6.05),   23: (20.84, 20.85),
    }
    return C_VALUES.get(term_idx, (0, 0))


def get_hour_pillar(day_stem_idx, hour, minute=0):
    """Compute hour pillar (时柱)."""
    # Determine 时辰 branch
    total_minutes = hour * 60 + minute

    if total_minutes >= 1380 or total_minutes < 60:  # 23:00 - 01:00
        h_branch = 0  # 子
    elif total_minutes < 180:  # 01:00 - 03:00
        h_branch = 1  # 丑
    elif total_minutes < 300:  # 03:00 - 05:00
        h_branch = 2  # 寅
    elif total_minutes < 420:  # 05:00 - 07:00
        h_branch = 3  # 卯
    elif total_minutes < 540:  # 07:00 - 09:00
        h_branch = 4  # 辰
    elif total_minutes < 660:  # 09:00 - 11:00
        h_branch = 5  # 巳
    elif total_minutes < 780:  # 11:00 - 13:00
        h_branch = 6  # 午
    elif total_minutes < 900:  # 13:00 - 15:00
        h_branch = 7  # 未
    elif total_minutes < 1020:  # 15:00 - 17:00
        h_branch = 8  # 申
    elif total_minutes < 1140:  # 17:00 - 19:00
        h_branch = 9  # 酉
    elif total_minutes < 1260:  # 19:00 - 21:00
        h_branch = 10  # 戌
    else:  # 21:00 - 23:00
        h_branch = 11  # 亥

    # Hour stem from 五鼠遁
    first_hour_stem = FIVE_RAT[day_stem_idx]
    h_stem = (first_hour_stem + h_branch) % 10

    return h_stem, h_branch


def get_nayin(stem_idx, branch_idx):
    """Get 纳音 for a stem-branch pair."""
    cycle_idx = NAYIN_IDX_MAP.get((stem_idx, branch_idx))
    if cycle_idx is None:
        return "未知"
    return NAYIN[cycle_idx]


def get_ten_god(day_stem_idx, other_stem_idx):
    """Compute ten god (十神) name for other_stem relative to day_stem."""
    d_elem = ELEMENTS[day_stem_idx]
    o_elem = ELEMENTS[other_stem_idx]
    same_yy = STEM_YY[day_stem_idx] == STEM_YY[other_stem_idx]

    if day_stem_idx == other_stem_idx:
        return "比肩"

    if d_elem == o_elem:
        return "劫财" if not same_yy else "比肩"

    # day generates other
    if GEN_BY[o_elem] == d_elem:
        return "食神" if same_yy else "伤官"

    # other generates day
    if GEN_BY[d_elem] == o_elem:
        return "偏印" if same_yy else "正印"

    # day controls other
    if CTRL_BY[o_elem] == d_elem:
        return "偏财" if same_yy else "正财"

    # other controls day
    if CTRL_BY[d_elem] == o_elem:
        return "七杀" if same_yy else "正官"

    return "未知"


def get_hidden_stems_info(branch_idx):
    """Get list of {stem_idx, stem, ten_god, strength} for a branch's hidden stems."""
    return HIDDEN_STEMS.get(branch_idx, [])


def get_dayun(year_stem_idx, month_stem_idx, month_branch_idx,
              birth_date, prev_jie_date, next_jie_date, gender):
    """Compute major luck cycles (大运)."""
    # Determine direction
    year_is_yang = STEM_YY[year_stem_idx] == "阳"
    is_male = gender == "male"

    go_forward = (year_is_yang and is_male) or (not year_is_yang and not is_male)

    # Calculate starting age
    if go_forward:
        target_date = next_jie_date
    else:
        target_date = prev_jie_date

    days_diff = abs((birth_date - target_date).days)
    start_age = round(days_diff / 3.0)

    dayun_list = []
    for i in range(8):
        age = start_age + i * 10
        if go_forward:
            dy_stem = (month_stem_idx + 1 + i) % 10
            dy_branch = (month_branch_idx + 1 + i) % 12
            direction = "顺排"
        else:
            dy_stem = (month_stem_idx - 1 - i) % 10
            dy_branch = (month_branch_idx - 1 - i) % 12
            direction = "逆排"

        dayun_list.append({
            "start_age": age,
            "stem": STEMS[dy_stem],
            "stem_idx": dy_stem,
            "branch": BRANCHES[dy_branch],
            "branch_idx": dy_branch,
            "nayin": get_nayin(dy_stem, dy_branch),
            "direction": direction,
        })

    return dayun_list, start_age, days_diff


def get_shensha(pillars, day_stem_idx, year_stem_idx, year_branch_idx):
    """Compute spirit stars (神煞) for each pillar."""
    # 天乙贵人: based on day stem (also year stem)
    TIANYI_MAP = {
        0: [1, 7], 1: [1, 7],  # 甲戊庚 -> 丑未
        2: [0, 8], 3: [0, 8],  # 乙己 -> 子申
        4: [9, 3], 5: [9, 3],  # 丙丁 -> 亥酉
        6: [6, 2],              # 辛 -> 午寅
        7: [5, 3], 8: [5, 3],  # 壬癸 -> 巳卯
    }

    # 文昌: based on day stem
    WENCHANG_MAP = {
        0: 5, 1: 6, 2: 8, 3: 9, 4: 8,
        5: 9, 6: 11, 7: 0, 8: 2, 9: 3,
    }

    # 桃花 (咸池): based on year/month branch
    TAOHUA_MAP = {
        2: 9, 3: 6, 4: 9,   # 寅午戌 -> 卯
        8: 9, 0: 9, 5: 9,   # 申子辰 -> 酉
        5: 6, 9: 6, 1: 6,   # 巳酉丑 -> 午
        11: 0, 3: 0, 7: 0,  # 亥卯未 -> 子
    }

    # 驿马: based on year branch
    YIMA_MAP = {
        2: 8, 6: 8, 10: 8,  # 寅午戌 -> 申
        8: 2, 0: 2, 4: 2,   # 申子辰 -> 寅
        5: 11, 9: 11, 1: 11, # 巳酉丑 -> 亥
        11: 5, 3: 5, 7: 5,  # 亥卯未 -> 巳
    }

    # 华盖: based on year branch
    HUAGAI_MAP = {
        2: 10, 6: 10, 10: 10, # 寅午戌 -> 戌
        8: 4, 0: 4, 4: 4,    # 申子辰 -> 辰
        5: 1, 9: 1, 1: 1,    # 巳酉丑 -> 丑
        11: 7, 3: 7, 7: 7,   # 亥卯未 -> 未
    }

    # 禄神: based on day stem
    LUSHEN_MAP = {0: 2, 1: 3, 2: 5, 3: 6, 4: 5, 5: 6, 6: 8, 7: 9, 8: 11, 9: 0}

    # 羊刃: based on day stem
    YANGREN_MAP = {0: 3, 1: 2, 2: 6, 3: 5, 4: 6, 5: 5, 6: 9, 7: 8, 8: 0, 9: 11}

    tianyi_branches = set(TIANYI_MAP.get(day_stem_idx, []))
    # Also check year stem
    tianyi_branches |= set(TIANYI_MAP.get(year_stem_idx, []))
    wenchang_branch = WENCHANG_MAP.get(day_stem_idx)
    taohua_branch = TAOHUA_MAP.get(year_branch_idx)
    yima_branch = YIMA_MAP.get(year_branch_idx)
    huagai_branch = HUAGAI_MAP.get(year_branch_idx)
    lushen_branch = LUSHEN_MAP.get(day_stem_idx)
    yangren_branch = YANGREN_MAP.get(day_stem_idx)

    shensha = {}
    for pillar_name, s_idx, b_idx in pillars:
        stars = []
        if b_idx in tianyi_branches:
            stars.append("天乙贵人")
        if b_idx == wenchang_branch:
            stars.append("文昌")
        if b_idx == taohua_branch:
            stars.append("桃花")
        if b_idx == yima_branch:
            stars.append("驿马")
        if b_idx == huagai_branch:
            stars.append("华盖")
        if b_idx == lushen_branch:
            stars.append("禄神")
        if b_idx == yangren_branch:
            stars.append("羊刃")

        if b_idx == 0:
            stars.append("将星") if b_idx == 0 else None  # placeholder

        shensha[pillar_name] = stars

    # 将星: based on year branch
    JIANGXING_MAP = {
        2: 6, 6: 6, 10: 6,  # 寅午戌 -> 午
        8: 0, 0: 0, 4: 0,   # 申子辰 -> 子
        5: 9, 9: 9, 1: 9,   # 巳酉丑 -> 酉
        11: 3, 3: 3, 7: 3,  # 亥卯未 -> 卯
    }
    jiangxing_branch = JIANGXING_MAP.get(year_branch_idx)

    for pillar_name, s_idx, b_idx in pillars:
        if b_idx == jiangxing_branch:
            shensha[pillar_name].append("将星")

    return shensha


def get_wuxing_counts(day_stem_idx, pillars_data):
    """Count five elements across all pillars (stems + branches)."""
    counts = {"木": 0, "火": 0, "土": 0, "金": 0, "水": 0}

    # Day stem
    counts[ELEMENTS[day_stem_idx]] += 1

    # Each pillar stem and branch
    branch_elements = ["水", "土", "木", "木", "土", "火", "火", "土", "金", "金", "土", "水"]

    for pname, s_idx, b_idx in pillars_data:
        counts[ELEMENTS[s_idx]] += 1
        counts[branch_elements[b_idx]] += 1

    return counts


def format_chart_output(year, month, day, hour, minute, gender):
    """Main calculation and formatting function."""
    y_s, y_b = get_year_pillar_for_date(year, month, day)
    d_s, d_b = get_day_pillar(year, month, day)
    m_s, m_b, prev_jie, next_jie = get_month_pillar(year, month, day, y_s)
    h_s, h_b = get_hour_pillar(d_s, hour, minute)
    birth_date = date(year, month, day)

    pillars = [
        ("year", y_s, y_b),
        ("month", m_s, m_b),
        ("day", d_s, d_b),
        ("hour", h_s, h_b),
    ]

    # Hidden stems for each branch
    hidden_info = {}
    for pname, s_idx, b_idx in pillars:
        hs_list = get_hidden_stems_info(b_idx)
        hidden_info[pname] = [
            {"stem": STEMS[hs[0]], "stem_idx": hs[0], "ten_god": get_ten_god(d_s, hs[0]),
             "strength": hs[1]}
            for hs in hs_list
        ]

    # Ten gods for stems and branch本气
    ten_gods = {}
    for pname, s_idx, b_idx in pillars:
        main_hidden = get_hidden_stems_info(b_idx)[0][0] if get_hidden_stems_info(b_idx) else b_idx
        ten_gods[pname] = {
            "stem_tg": get_ten_god(d_s, s_idx),
            "branch_tg": get_ten_god(d_s, main_hidden),
            "branch_tg_stem": STEMS[main_hidden],
        }

    # Five elements
    branch_elements = ["水", "土", "木", "木", "土", "火", "火", "土", "金", "金", "土", "水"]
    five_elems = {}
    for pname, s_idx, b_idx in pillars:
        five_elems[pname] = {
            "stem": ELEMENTS[s_idx],
            "branch": branch_elements[b_idx],
        }

    # Na Yin
    nayins = {}
    for pname, s_idx, b_idx in pillars:
        nayins[pname] = get_nayin(s_idx, b_idx)

    # Wuxing counts
    wuxing_counts = get_wuxing_counts(d_s, pillars)

    # Major luck
    prev_jie_date = prev_jie[1]
    next_jie_date = next_jie[1]
    dayun, start_age_rounded, start_age_days = get_dayun(
        y_s, m_s, m_b, birth_date, prev_jie_date, next_jie_date, gender)

    # Shensha
    shensha = get_shensha(pillars, d_s, y_s, y_b)

    return {
        "birth": {
            "year": year, "month": month, "day": day,
            "hour": hour, "minute": minute, "gender": gender,
            "shichen": BRANCHES[h_b] + "时",
        },
        "pillars": {
            "year": {"stem": STEMS[y_s], "stem_idx": y_s, "branch": BRANCHES[y_b],
                     "branch_idx": y_b, "nayin": nayins["year"]},
            "month": {"stem": STEMS[m_s], "stem_idx": m_s, "branch": BRANCHES[m_b],
                      "branch_idx": m_b, "nayin": nayins["month"]},
            "day": {"stem": STEMS[d_s], "stem_idx": d_s, "branch": BRANCHES[d_b],
                    "branch_idx": d_b, "nayin": nayins["day"]},
            "hour": {"stem": STEMS[h_s], "stem_idx": h_s, "branch": BRANCHES[h_b],
                     "branch_idx": h_b, "nayin": nayins["hour"]},
        },
        "day_master": {
            "stem": STEMS[d_s], "stem_idx": d_s,
            "element": ELEMENTS[d_s], "yin_yang": STEM_YY[d_s],
        },
        "ten_gods": ten_gods,
        "five_elements": five_elems,
        "hidden_stems": hidden_info,
        "wuxing_counts": wuxing_counts,
        "dayun": dayun,
        "start_age": start_age_rounded,
        "start_age_days": start_age_days,
        "shensha": shensha,
        "solar_terms": {
            "prev_jie": prev_jie[0],
            "next_jie": next_jie[0],
            "prev_jie_date": str(prev_jie_date),
            "next_jie_date": str(next_jie_date),
        },
        "sixty_cycle_idx": {
            "year": NAYIN_IDX_MAP.get((y_s, y_b), -1),
            "month": NAYIN_IDX_MAP.get((m_s, m_b), -1),
            "day": NAYIN_IDX_MAP.get((d_s, d_b), -1),
            "hour": NAYIN_IDX_MAP.get((h_s, h_b), -1),
        },
        "boundary_warning": _check_boundary(birth_date, prev_jie_date, next_jie_date),
    }


def _check_boundary(birth_date, prev_jie_date, next_jie_date):
    """Check if birth is near a solar term boundary (within 1 day)."""
    prev_diff = abs((birth_date - prev_jie_date).days)
    next_diff = abs((birth_date - next_jie_date).days)
    if prev_diff <= 1 or next_diff <= 1:
        return ("出生日期接近节气交界（{}天），月柱可能因具体出生时辰而异，"
                "建议核实。".format(min(prev_diff, next_diff)))
    return None


# ============================================================
# Main Entry Point
# ============================================================

def main():
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            print(json.dumps({"error": "No input provided"}, ensure_ascii=False))
            sys.exit(1)
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON: {e}"}, ensure_ascii=False))
        sys.exit(1)

    required = ["year", "month", "day", "hour", "gender"]
    missing = [k for k in required if k not in data]
    if missing:
        print(json.dumps(
            {"error": f"Missing required fields: {', '.join(missing)}"},
            ensure_ascii=False))
        sys.exit(1)

    year = int(data["year"])
    month = int(data["month"])
    day = int(data["day"])
    hour = int(data["hour"])
    minute = int(data.get("minute", 0))
    gender = str(data["gender"]).lower()

    if gender not in ("male", "female", "男", "女"):
        gender = "male"  # default

    if gender == "男":
        gender = "male"
    elif gender == "女":
        gender = "female"

    # Validate date
    try:
        date(year, month, day)
    except ValueError as e:
        print(json.dumps({"error": f"Invalid date: {e}"}, ensure_ascii=False))
        sys.exit(1)

    result = format_chart_output(year, month, day, hour, minute, gender)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
